import { useState } from 'react'
import { AvatarFigure } from '../components/AvatarFigure'
import { Icon } from '../components/Icons'
import type { WorkoutSession } from '../types'
import sakuraGloves from '../assets/equipment/gloves/sakura_gloves.png'
import { POSE_ISSUE_COPY } from '../lib/poseFeedback'
import type { PoseIssue } from '../types'

const fmt=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`
export function Summary({ result, avatar, home }: { result: WorkoutSession; avatar: () => void; home: () => void }) {
  const [reward, setReward] = useState(result.unlocked.includes('sakura_gloves'))
  const grade = result.formScore >= 90 ? 'S' : result.formScore >= 80 ? 'A' : result.formScore >= 70 ? 'B' : 'C'
  const zones = [result.zone1Seconds, result.zone2Seconds, result.zone3Seconds, result.zone4Seconds, result.zone5Seconds]
  const corrections = (Object.entries(result.correctionCounts || {}) as [PoseIssue, number][]).filter(([, count]) => count > 0).sort((a, b) => b[1] - a[1])
  const breakdown = [
    ['下蹲深度', result.formBreakdown?.depth || 0], ['膝盖稳定', result.formBreakdown?.stability || 0],
    ['躯干控制', result.formBreakdown?.trunk || 0], ['左右对称', result.formBreakdown?.symmetry || 0],
  ] as const
  return <div className="page summary-page"><div className="summary-hero"><span className="eyebrow">WORKOUT COMPLETE</span><h2>训练完成！</h2><p>今天不只是完成了，你还留下了清楚的进步线索。</p><div className="summary-avatar"><AvatarFigure view="front"/></div><div className="xp-earned">+{result.xpEarned} <small>XP</small></div></div><section className="summary-sheet"><div className="score-title"><div className="big-score">{result.formScore}<small>分</small></div><div><b>{result.formScore>=90?'稳定完成这一组':'这一组认真做完了'}</b><span>{result.perfectReps} 次高质量动作 · {result.conversationTurnCount || 0} 轮陪练对话</span></div><span className="grade">{grade}</span></div><div className="summary-grid"><div><small>训练时长</small><b>{fmt(result.durationSeconds)}</b></div><div><small>完成次数</small><b>{result.reps} 次</b></div><div><small>平均心率</small><b>{result.averageBpm !== null ? `${result.averageBpm} BPM` : '无数据'}</b></div><div><small>最高心率</small><b>{result.maxBpm !== null ? `${result.maxBpm} BPM` : '无数据'}</b></div></div><div className="form-breakdown"><div className="section-title"><b>动作维度</b><span>本地 MediaPipe</span></div>{breakdown.map(([label, score]) => <div key={label}><span>{label}</span><i><b style={{ width: `${score}%` }}/></i><em>{score || '--'}</em></div>)}</div><div className="correction-summary"><div className="section-title"><b>本组调整线索</b><span>{corrections.length ? '继续关注' : '整体稳定'}</span></div>{corrections.length ? corrections.slice(0, 3).map(([issue, count]) => <span key={issue}><b>{POSE_ISSUE_COPY[issue].label}</b><em>{count} 次</em></span>) : <p>没有持续出现的姿势问题，下一组继续保持节奏。</p>}</div>{result.visionInsights?.length > 0 && <div className="vision-summary"><div className="section-title"><b>视觉复核摘要</b><span>不保存图片</span></div><p>{result.visionInsights[result.visionInsights.length - 1].summary}</p></div>}<div className="zone-summary">{zones.map((seconds,index)=><div key={index}><span>Zone {index+1}</span><b>{fmt(seconds)}</b></div>)}</div><div className="reward-row"><Icon name="spark"/><span><b>成长已记录</b><small>{result.heartRateSource==='ble'?'心率来源：BLE 设备':'本次未收到 BLE 心率包'}</small></span><em>+{result.xpEarned} XP</em></div><button className="primary" onClick={avatar}>查看我的形象 <Icon name="arrow"/></button><button className="text-btn" onClick={home}>返回首页</button></section>{reward&&<div className="modal-backdrop"><div className="reward-modal"><button className="modal-close" onClick={()=>setReward(false)}>×</button><span className="eyebrow">ACHIEVEMENT UNLOCKED</span><img className="pixel-art reward-equipment-image" src={sakuraGloves} alt="樱花手套"/><h3>精准掌控</h3><p>完成一次动作评分 90+ 的训练</p><div className="unlocked-item"><img className="pixel-art unlocked-equipment-image" src={sakuraGloves} alt="樱花手套"/><div><small>正式装备</small><b>樱花手套</b></div><em>N</em></div><button className="primary" onClick={()=>{setReward(false);avatar()}}>立即去装备</button></div></div>}</div>
}
